name: Publish to registries
on:
  push:
    branches:
      - main
    paths:
      - 'deno.json'
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'ltgcgo/kd-tree'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4

      - name: Publish package
        run: "./shx publish"